### ISSUE TITLE
`npm start` script crashes when attempting to output to static/bundle.js

### ISSUE THREAD

**Issue by azinge** [RyTaus/sleek#2]
Issue:
Running `npm start` on OSX produces the error -
```
Error: ENOENT: no such file or directory, open '/src/static/bundle.js'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! visualjs@0.0.1 build: `browserifyinc /src/drawer.js -o /src/static/bundle.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the visualjs@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Potential Cause:
I believe this error is due to the browserifyinc script attempting to write to bundle.js, but crashing on startup due to the file not existing. The problem was resolved on my machine by simply adding a static/bundle.js file to the repository myself, although I'm not sure whether or not @RyTaus approves of having a base version of this file be included with the repository in it's entirety.

**Comment by RyTaus** [comment]
Eliminated the need for bundling. Fixed.
